version: "1"

services:
  - type: web
    name: ifixit-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
    healthCheckPath: /
    autoDeploy: true

